package interval;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import static org.hamcrest.CoreMatchers.not;
import static org.hamcrest.core.Is.is;
import static org.junit.Assert.assertThat;

public class ClosedIntervalTest extends AbstractIntervalTest {

    public Interval createInterval(int lower, int upper) {
        return Interval.createClosedInterval(lower, upper);
    }

    @Override
    protected boolean includesLowerEndpoint() {
        return true;
    }

    @Override
    protected boolean includesUpperEndpoint() {
        return true;
    }

    @Test
    public void testToString() {
        assertThat(interval.toString(), is("[1-3]"));
    }
}
