package interval;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import static org.hamcrest.core.Is.is;
import static org.junit.Assert.assertThat;

public class IntervalTest {

    @Test
    public void testCreateClosedInterval() {
        Interval interval = new Interval(1, 3);
        assertThat(interval.getLowerEndpoint(), is(1));
        assertThat(interval.getUpperEndpoint(), is(3));
    }
}
