package interval;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class ClosedInterval {

    public static Interval createClosedInterval(int lower, int upper) {
        return new Interval(new ClosedEndpoint(lower), new ClosedEndpoint(upper));
    }
}
