package interval;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class ClosedInterval extends Interval {

    private ClosedInterval(int lowerEndpoint, int upperEndpoint) {
        super(new ClosedEndpoint(lowerEndpoint), new ClosedEndpoint(upperEndpoint));
    }

    public static Interval createClosedInterval(int lower, int upper) {
        return new ClosedInterval(lower, upper);
    }
}
