package interval;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Interval {
    private final int lowerEndpoint;
    private int upperEndpoint;

    public Interval(int lowerEndpoint, int upperEndpoint) {
        this.lowerEndpoint = lowerEndpoint;
        this.upperEndpoint = upperEndpoint;

    }

    public int getLowerEndpoint() {
        return lowerEndpoint;
    }

    public int getUpperEndpoint() {
        return upperEndpoint;
    }
}
